name: Test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      # cache
      
      - name: Test
        run: docker-compose run --rm app /bin/bash -c "dum i && dum rw lint --fix && dum rw test --no-watch"
